export const artists = [
  {
    id: "anthony-beastmode",
    name: "Anthony Beastmode",
    genre: "Electronic • Viral",
    image: "/images/anthony.jpg",
    heroImage: "/images/anthony.jpg",
    bio: "High-energy viral anthems with aggressive synths.",
    email: "booking@anthony.com",
    phone: "+1 555 111 2222",
    personnel: "Sarah (Manager)",
  },
  {
    id: "kev-train",
    name: "Kev Train",
    genre: "EDM • Festival",
    image: "/images/kev train.jpg",
    heroImage: "/images/kev train.jpg",
    bio: "Mainstage EDM built for festival crowds.",
    email: "booking@kevtrain.com",
    phone: "+1 555 222 3333",
    personnel: "Marcus (Booking)",
  },
  {
    id: "mike-chandler",
    name: "Mike Chandler",
    genre: "Indie • Alt",
    image: "/images/mike.jpg",
    heroImage: "/images/mike.jpg",
    bio: "Ethereal guitars and raw lyrics.",
    email: "contact@mikechandler.com",
    phone: "+1 555 333 4444",
    personnel: "Elena (Publicist)",
  },
  {
    id: "brian",
    name: "Brian",
    genre: "Rap • Street",
    image: "/images/brian.png",
    heroImage: "/images/brian.png",
    bio: "Raw street storytelling.",
    email: "brian@label.com",
    phone: "+1 555 444 5555",
    personnel: "Dre (A&R)",
  },
  {
    id: "ty-march",
    name: "Ty March",
    genre: "Chill • Ambient",
    image: "/images/ty march.png",
    heroImage: "/images/ty march.png",
    bio: "Minimal ambient soundscapes.",
    email: "ty@ambient.com",
    phone: "+1 555 555 6666",
    personnel: "Chloe (Sync)",
  },
  {
    id: "jankster",
    name: "Jankster",
    genre: "Lo-Fi • Night",
    image: "/images/jank.png",
    heroImage: "/images/jank.png",
    bio: "Lo-fi beats with jazz textures.",
    email: "jank@lofi.com",
    phone: "+1 555 666 7777",
    personnel: "Leo (Digital)",
  },
];
