export const artists = [
  {
    id: "anthony-beastmode",
    name: "Anthony Beastmode",
    genre: "Electronic • Viral",
    image: "/images/anthony.jpg",
    heroImage: "/images/anthony.jpg",
    bio: "Anthony Beastmode is a high-energy electronic creator known for explosive drops, aggressive synth work, and sounds built for viral moments. His music thrives on intensity, fast builds, and punchy basslines that translate perfectly to TikTok edits, workouts, and high-impact visuals. Blending producer precision with creator instincts, Anthony crafts tracks designed to hit instantly and leave a lasting impression.",
    email: "Support@Tokhubflow.com",
    phone: "±1 301 531 5445",
    personnel: "Sarah (Manager)",
    videos: [
      {
        title: "Beastmode Drop",
        description: "High-energy drop built for viral edits.",
        src: "/videos/beaste1.mp4",
      },
      {
        title: "Workout Anthem",
        description: "Perfect for gym and motivation clips.",
        src: "/videos/beast2.mp4",
      },
      {
        title: "looking good",
        description: "Time to look nice.",
        src: "/videos/beaste3.mp4",
      },
    ],
  },
  {
    id: "kev-train",
    name: "Kev Train",
    genre: "EDM • Festival",
    image: "/images/kev train.jpg",
    heroImage: "/images/kev train.jpg",
    bio: "Kev Train delivers festival-ready EDM with massive drops, uplifting energy, and polished production. His sound is engineered for big moments — from mainstage-style builds to viral TikTok transitions. Kev uses TikTok as a creative testing ground, crafting tracks that move crowds and connect instantly with dance, fitness, and cinematic creators.",
    email: "Support@Tokhubflow.com",
    phone: "±1 301 531 5445",
    personnel: "Marcus (Booking)",
    videos: [
      {
        title: "kev train Drop",
        description: " viral edits.",
        src: "/videos/kev/kev.mp4",
      },
      {
        title: "just a  reel",
        description: "just a reel video.",
        src: "/videos/kev/kev2.mp4",
      },
      {
        title: "unboxing fun",
        description: "Time to unbox.",
        src: "/videos/kev/kev3.mp4",
      },
    ],
  },
  {
    id: "mike-chandler",
    name: "Mike Chandler",
    genre: "Indie • Alt",
    image: "/images/mike.jpg",
    heroImage: "/images/mike.jpg",
    bio: "Mike Chandler is an indie-alternative creator whose sound leans into emotion, atmosphere, and honesty. With ethereal guitar textures and introspective lyrics, his music resonates with storytelling creators and late-night listeners. Mike’s presence on TikTok feels personal and authentic, inviting fans into a world built on mood, vulnerability, and connection.",
    email: "Support@Tokhubflow.com",
    phone: "±1 301 531 5445",
    personnel: "Elena (Publicist)",
    videos: [
      {
        title: "Chadler reel",
        description: "doing somehting fun.",
        src: "/videos/chandler/chad.mp4",
      },
      {
        title: "Do your thing ",
        description: " motivation clips.",
        src: "/videos/chandler/chad1.mp4",
      },
      {
        title: "Dont care about others opinion",
        description: "just win .",
        src: "/videos/chandler/chad2.mp4",
      },
    ],
  },
  {
    id: "brian",
    name: "Brian",
    genre: "Rap • Street",
    image: "/images/brian.png",
    heroImage: "/images/brian.png",
    bio: "Brian brings raw street energy and unfiltered storytelling to TikTok. His music reflects real experiences, sharp lyricism, and beats that hit with purpose. Rather than chasing trends, Brian uses sound as a voice — connecting with creators and listeners who value authenticity, grit, and substance.",
    email: "Support@Tokhubflow.com",
    phone: "±1 301 531 5445",
    personnel: "Dre (A&R)",
    videos: [
      {
        title: "Beastmode Drop",
        description: "High-energy drop built for viral edits.",
        src: "/videos/brian/bmoe72 (1).mp4",
      },
      {
        title: "Workout Anthem",
        description: "Perfect for gym and motivation clips.",
        src: "/videos/brian/bmoe72 (2).mp4",
      },
      {
        title: "looking good",
        description: "Time to look nice.",
        src: "/videos/brian/bmoe72 (3).mp4",
      },
    ],
  },
  {
    id: "ty-march",
    name: "Ty March",
    genre: "Chill • Ambient",
    image: "/images/ty march.png",
    heroImage: "/images/ty march.png",
    bio: "Ty March creates calm, minimal ambient soundscapes designed for focus, reflection, and atmosphere. His music pairs seamlessly with scenic visuals, study sessions, and late-night TikTok moments. Subtle and intentional, Ty’s sound invites listeners to slow down and connect through space, texture, and emotion.",
    email: "Support@Tokhubflow.com",
    phone: "±1 301 531 5445",
    personnel: "Chloe (Sync)",
    videos: [
      {
        title: "Beastmode Drop",
        description: "High-energy drop built for viral edits.",
        src: "/videos/tymarch/Download (1).mp4",
      },
      {
        title: "Workout Anthem",
        description: "Perfect for gym and motivation clips.",
        src: "/videos/tymarch/Download (2).mp4",
      },
      {
        title: "looking good",
        description: "Time to look nice.",
        src: "/videos/tymarch/Download.mp4",
      },
    ],
  },
  {
    id: "jankster",
    name: "Jankster",
    genre: "Lo-Fi • Night",
    image: "/images/jank.png",
    heroImage: "/images/jank.png",
    bio: "Jankster is a lo-fi creator known for warm textures, jazzy undertones, and late-night vibes. His beats feel lived-in and relaxed, making them ideal for chill edits, creative routines, and reflective storytelling. On TikTok, Jankster’s music sets the mood — becoming the atmosphere behind the moment rather than the spotlight itself.",
    email: "Support@Tokhubflow.com",
    phone: "±1 301 531 5445",
    personnel: "Leo (Digital)",
    videos: [
      {
        title: "ice furr",
        description: "she just love the cold ",
        src: "/videos/janister/janister.mp4",
      },
      {
        title: "Workout Anthem",
        description: "Perfect for gym and motivation clips.",
        src: "/videos/janister/janister1.mp4",
      },
      {
        title: "looking good",
        description: "Time to look nice.",
        src: "/videos/janister/janister2.mp4",
      },
    ],
  },
  {
    id: "kylecoulahan",
    name: "Kyle Coulahan",
    genre: "country music , soul music",
    image: "/images/kyle.jpg",
    heroImage: "/images/kyledad.jpg",
    bio: "Kyle Coulahan is a country and soul artist known for heartfelt songwriting, warm grooves, and a laid-back, lived in sound. His music blends classic country storytelling with soulful undertones, creating songs that feel honest and familiar. On TikTok, Kyle’s tracks set the tone  soundtracking real moments, quiet reflections, and everyday stories rather than demanding the spotlight.",
    email: "Support@Tokhubflow.com",
    phone: "±1 301 531 5445",
    personnel: "Leo (Digital)",
    videos: [
      {
        title: "cold heart summer",
        description: "chill energy with a frosty edge.",
        src: "/videos/kyle/kyle1.mp4",
      },
      {
        title: "push through",
        description: "soundtrack for reps, sweat, and staying focused.",
        src: "/videos/kyle/kyle2.mp4",
      },
      {
        title: "clean cut moments",
        description: "when everything feels dialed in just right.",
        src: "/videos/kyle/kyle3.mp4",
      },
    ],
  },
  {
    id: "zacharybruno",
    name: "Zachary Bruno",
    genre: "Country • Night • Lifestyle",
    image: "/images/zach.jpg",
    heroImage: "/images/zach.jpg",
    bio: "Zachary Bruno is a country and lifestyle artist known for heartfelt songwriting, warm grooves, and a laid-back, lived in sound. His music blends classic country storytelling with soulful undertones, creating songs that feel honest and familiar. On TikTok, Zachary’s tracks set the tone soundtracking real moments, quiet reflections, and everyday stories rather than demanding the spotlight.",
    email: "Support@Tokhubflow.com",
    phone: "±1 301 531 5445",
    personnel: "Leo (Digital)",
    videos: [
      {
        title: "ice furr",
        description: "she just love the cold ",
        src: "/videos/jack/jack.mp4",
      },
      {
        title: "Workout Anthem",
        description: "Perfect for gym and motivation clips.",
        src: "/videos/jack/jack1.mp4",
      },
      {
        title: "looking good",
        description: "Time to look nice.",
        src: "/videos/jack/jack2.mp4",
      },
    ],
  },
];
